apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cf-web
  name: deployment-v2
  namespace: default
spec:
  minReadySeconds: 0
  replicas: 2
  selector:
    matchLabels:
      app: cf-web
  template:
    metadata:
      labels:
        app: cf-web
    spec:
      containers:
      - image: cferber/cf-web:green
        name: cf-web
        ports:
        - containerPort: 80
