apiVersion: v1
kind: ReplicationController
metadata:
  name: centos-test-dev                  # nom du RC et des PODS
spec:
  replicas: 2
  selector:
    app: centos-test-dev
  template:
    metadata:
      #generateName: centos-test-dev-   # INUTILE car surcharge par: nom du RC-xxxxx
      labels:
        app: centos-test-dev
    spec:
      containers:
        - name: centos-test-dev-container   # Nom du container docker : centos-test-dev_container.<ID>  (docker ps)
          image: alexfr75/centos_test_dev:1.0


---


apiVersion: v1
kind: Service
metadata:
  name: centos-test-dev    # nom du Service
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
  selector:
    app: centos-test-dev
